service: ailog-bot
# app and org for use with dashboard.serverless.com
app: ailog-app
org: hunkim

provider:
  name: aws
  runtime: python3.8
  region: us-west-2
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "kendra:*"
        - "dynamodb:*"

      Resource:
        - "*"

functions:
  queryAPI:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
    environment:
      LINE_CHANNEL_SECRET: ${file(../config.json):LINE_CHANNEL_SECRET}
      LINE_CHANNEL_ACCESS_TOKEN: ${file(../config.json):LINE_CHANNEL_ACCESS_TOKEN}

resources: # CloudFormation template syntax
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        BillingMode: PAY_PER_REQUEST
        TableName: ailogTable5
        AttributeDefinitions:
          - AttributeName: url
            AttributeType: S
        KeySchema:
          - AttributeName: url
            KeyType: HASH


custom:
  wsgi:
    app: app.app
    pythonBin: python3.8 # Some systems with Python3 may require this
    packRequirements: false

plugins:
  - serverless-wsgi
  - serverless-python-requirements